# Generated by Django 5.1.2 on 2024-12-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Designer'), (2, 'Reception'), (3, 'SuperDesigner'), (0, 'Admin')], null=True),
        ),
    ]
