# Generated by Django 5.1.2 on 2024-12-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp_user_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestManger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
