# Generated by Django 5.1.2 on 2024-12-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_chatmassage_delete_testmanger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmassage',
            name='user',
        ),
    ]
