# Generated by Django 5.1.2 on 2024-12-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_chatmassage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmassage',
            name='user',
        ),
    ]
