# Generated by Django 5.1.2 on 2024-12-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_chatmassage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmassage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
