# Generated by Django 5.1.6 on 2025-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
