# Generated by Django 5.1.6 on 2025-03-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Designer'), (2, 'Reception'), (3, 'SuperDesigner'), (0, 'Admin'), (4, 'Printer'), (5, 'Delivered'), (6, 'Digital'), (7, 'Bill'), (8, 'Chaspac'), (9, 'Shop role'), (10, 'Laser')], null=True),
        ),
    ]
