# Generated by Django 5.1.6 on 2025-03-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionorder',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
