# Generated by Django 5.1.2 on 2024-12-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributetype',
            name='attribute_type',
        ),
    ]
