# Generated by Django 5.1.2 on 2024-12-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_remove_attributetype_attribute_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='type',
        ),
        migrations.AddField(
            model_name='attributetype',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.attributechoice'),
        ),
    ]
