# Generated by Django 5.1.2 on 2024-12-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_attributevalue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('Done', 'Done')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ReceptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receive_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reminder_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.order')),
            ],
        ),
    ]
