# Generated by Django 5.1.6 on 2025-03-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_category_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Designer'), (2, 'Reception'), (3, 'SuperDesigner'), (0, 'Admin'), (4, 'Printer'), (5, 'Delivered'), (6, 'Digital'), (7, 'Bill'), (8, 'Chaspak'), (9, 'Shop role'), (10, 'Laser')], max_length=50, null=True),
        ),
    ]
