# Generated by Django 5.1.2 on 2024-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_order_attributes_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='attribute_type',
            field=models.CharField(choices=[('dropdown', 'dropdown'), ('date', 'date'), ('checkbox', 'checkbox'), ('input', 'input'), ('radio', 'radio')], default='select attribute type', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('processing', 'Processing'), ('done', 'Done')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='AttributeChoice',
        ),
    ]
