# Generated by Django 5.1.2 on 2025-02-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_receptionorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('processing', 'Processing'), ('done', 'Done'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
