# Generated by Django 5.1.6 on 2025-02-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='attribute_type',
            field=models.CharField(choices=[('dropdown', 'dropdown'), ('date', 'date'), ('checkbox', 'checkbox'), ('input', 'input')], default='select attribute type', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'attribute_value')},
        ),
    ]
